"""Generate the repo-root README.md (intro + per-network feed tables + footer).

Usage (from anywhere):
    python script/generate-readme.py           # write README.md
    python script/generate-readme.py --check   # exit 1 if README.md is stale
    python script/generate-readme.py --stdout  # print instead of writing

Malformed config files are skipped with a warning on stderr. Output is
deterministic apart from the footer year.
"""
import argparse
import datetime
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / 'README.md'
BASE_URL = 'https://config.orakl.network'
NETWORKS = ('cypress', 'baobab')
INTERVALS = ('fetchInterval', 'aggregateInterval', 'submitInterval')

INTRO = """\
<!-- Generated by script/generate-readme.py — do not edit by hand. CI regenerates it on every PR. -->

# orakl-config

Price-feed configuration for the Orakl Network oracle, per network (`cypress` = Kaia mainnet, `baobab` = Kaia testnet).

## Served bundles

| network | price feeds | mag7 feeds |
| --- | --- | --- |
""" + ''.join(
    '| {n} | [`{n}_configs.json`]({u}/{n}_configs.json) | [`{n}_mag7.json`]({u}/{n}_mag7.json) |\n'.format(n=n, u=BASE_URL)
    for n in NETWORKS
) + """
## Layout

- `config/<network>/<PAIR>.config.json` — per-pair feed definitions (fetch / aggregate / submit intervals in ms, and the data-source feeds).
- `mag7/<network>/<name>.json` — mag7 (US equity) feed definitions.
- `<network>_configs.json` / `<network>_mag7.json` — aggregated bundles served from the repo root.

See [`script/README.md`](script/README.md) for the scripts that generate the bundles and this file.
"""


def valid_interval(value):
    # Any JSON number, but not bool (which subclasses int).
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def warn(path, msg):
    print('skipping {}: {}'.format(path.relative_to(ROOT), msg), file=sys.stderr)


def cell(value):
    return str(value).replace('|', '\\|')


def source_name(feed):
    """wss feeds -> provider; others (DEX pools, HTTP) -> feed-name prefix."""
    definition = feed.get('definition')
    if isinstance(definition, dict) and definition.get('type') == 'wss' \
            and isinstance(definition.get('provider'), str):
        return definition['provider']
    name = feed.get('name')
    if isinstance(name, str) and name:
        return name.split('-', 1)[0]
    return None


def load_pair(path):
    """Return (name, sources, n_feeds, intervals) or None (with a warning) if malformed."""
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except (ValueError, OSError) as err:
        # ValueError covers JSONDecodeError and UnicodeDecodeError
        warn(path, 'could not read/parse JSON ({})'.format(err))
        return None
    if not isinstance(data, dict):
        warn(path, 'top-level JSON is not an object')
        return None
    feeds = data.get('feeds')
    if not isinstance(feeds, list):
        warn(path, '"feeds" missing, null, or not a list')
        return None
    bad = [k for k in INTERVALS if not valid_interval(data.get(k))]
    if not isinstance(data.get('name'), str):
        bad.insert(0, 'name')
    if bad:
        warn(path, 'field(s) missing or not the expected type: {}'.format(', '.join(bad)))
        return None
    sources = {source_name(feed) for feed in feeds if isinstance(feed, dict)}
    sources.discard(None)
    if feeds and not sources:
        warn(path, 'no feed has a usable name/provider')
        return None
    return data['name'], sorted(sources, key=lambda s: (s.lower(), s)), len(feeds), [data[k] for k in INTERVALS]


def network_table(network):
    rows = []
    feed_total = 0
    for path in sorted((ROOT / 'config' / network).glob('*.config.json')):
        pair = load_pair(path)
        if pair is None:
            continue
        name, sources, n_feeds, intervals = pair
        feed_total += n_feeds
        link = path.relative_to(ROOT).as_posix()
        rows.append('| [{}]({}) | {} | {} |'.format(
            cell(name), link, cell(', '.join(sources)), ' | '.join(cell(v) for v in intervals)))
    lines = [
        '## {}'.format(network.capitalize()),
        '',
        '{} pairs, {} feeds.'.format(len(rows), feed_total),
        '',
        '| pair | sources | ' + ' | '.join(INTERVALS) + ' |',
        '| --- | --- | ' + ' | '.join('---:' for _ in INTERVALS) + ' |',
    ] + rows
    return '\n'.join(lines) + '\n'


def render():
    year = datetime.date.today().year
    parts = [INTRO] + [network_table(n) for n in NETWORKS]
    parts.append('---\n\nMaintained by Bisonai · © 2022–{}\n'.format(year))
    return '\n'.join(parts)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = parser.add_mutually_exclusive_group()
    group.add_argument('--check', action='store_true', help='exit 1 if README.md is out of date')
    group.add_argument('--stdout', action='store_true', help='print to stdout instead of writing README.md')
    args = parser.parse_args()

    content = render()
    if args.stdout:
        sys.stdout.write(content)
        return 0
    current = README.read_text(encoding='utf-8') if README.exists() else ''
    if args.check:
        if current != content:
            print('README.md is out of date; run: python script/generate-readme.py', file=sys.stderr)
            return 1
        return 0
    if current != content:
        README.write_text(content, encoding='utf-8')
    return 0


if __name__ == '__main__':
    sys.exit(main())
